### ISSUE TITLE
Issue when loading ad - ConnectException

### ISSUE THREAD

**Issue by sierra-delta** [laurencedawson/AdColliderSdk#1]
Hi, I am using the library and everything else in my app is loading from the web.
This library is throwing a ConnectException error.

com.adcollider.sdk.volley.NoConnectionError: java.net.ConnectException: Failed to connect to ads.adcollider.com/167.172.239.93:443

I guess it's a server error?

**Comment by nedimf** [comment]
@laurencedawson

**Comment by sierra-delta** [comment]
Is this project still active?

**Comment by nedimf** [comment]
Yeah, I think so.

**Comment by laurencedawson** [comment]
@sierra-delta sorry for the delay in getting back to you. Should be up and running again now.
